repos:
    - repo: https://github.com/psf/black
      rev: 21.5b1
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.8.0
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "bc48c54"
      hooks:
          - id: prettier
