# Generated by Django 3.2.4 on 2021-06-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0002_remove_pin_image"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="pin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pins.pin",
            ),
        ),
    ]
