# Generated by Django 3.2.4 on 2021-07-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_alter_image_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
