# Generated by Django 3.2.3 on 2021-05-15 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePin",
            fields=[
                (
                    "pin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boards.pin",
                    ),
                ),
            ],
            bases=("boards.pin",),
        ),
        migrations.AlterField(
            model_name="pin",
            name="x_coordinate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pin",
            name="y_coordinate",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mimetype", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="images/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="images",
                        to="boards.imagepin",
                    ),
                ),
            ],
        ),
    ]
