# Generated by Django 3.2.3 on 2021-05-16 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_auto_20210515_2218"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="pin",
            name="author",
        ),
        migrations.AlterField(
            model_name="pin",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="board",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pins",
                to="boards.board",
            ),
            preserve_default=False,
        ),
    ]
