# Generated by Django 3.2.3 on 2021-05-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_auto_20210516_2337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="pin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="boards.pin",
            ),
        ),
        migrations.DeleteModel(
            name="ImagePin",
        ),
    ]
