# Generated by Django 3.2.3 on 2021-05-18 00:30

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("boards", "0008_alter_board_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="pin",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
