# Generated by Django 3.2.3 on 2021-06-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0009_auto_20210518_0030"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pin",
        ),
    ]
